# docker-compose file for creating a local development environment
version: '2'
services:

  web:
    image: webappbase:1.0    
    links:
      - consul

  consul:
    image: consul:latest
    ports:
      - "8500"
